### ISSUE TITLE
Nudged run fails with `layout=2,2`

### ISSUE THREAD

**Issue by oliverwm1** [VulcanClimateModeling/fv3gfs-util#44]
Getting a KeyError when reference state is being scattered in a "nudge-to-fine" run:
```
Traceback (most recent call last):
  File "/mnt/data/runfile.py", line 48, in <module>
    for time, diagnostics in loop:
  File "/fv3net/workflows/prognostic_c48_run/runtime/loop.py", line 263, in __iter__
    diagnostics.update(substep())
  File "/fv3net/workflows/prognostic_c48_run/runtime/loop.py", line 253, in _compute_python_tendency
    return self.stepper._compute_python_tendency()
  File "/fv3net/workflows/prognostic_c48_run/runtime/steppers/nudging.py", line 87, in _compute_python_tendency
    reference = self._get_reference_state(self._state.time)
  File "/fv3net/workflows/prognostic_c48_run/runtime/nudging.py", line 117, in _get_reference_state
    tracer_properties=tracer_metadata,
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/_legacy_restart.py", line 60, in open_restart
    state = communicator.tile.scatter_state(state)
  File "/usr/local/lib/python3.6/dist-packages/fv3gfs/util/communicator.py", line 282, in scatter_state
    if recv_state["time"] is None:
KeyError: 'time'
```
Possibly related to #38 and/or #39? @spencerkclark

**Comment by spencerkclark** [comment]
Indeed it was likely precipitated by that change, yes, but in principle it should be safe to scatter a state that does not include `"time"` as a key.  There's a fair bit of special logic around the `"time"` key within [`scatter_state`](https://github.com/VulcanClimateModeling/fv3gfs-util/blob/a76476749a02750a6e4d98612dad5a9dcd40356c/fv3gfs/util/communicator.py#L236-L284), so I'm guessing things are somehow getting hung up there.  I didn't look into that while writing #39, though in hindsight the special logic is perhaps not a surprise since `"time"` is currently the only possible key in a state dictionary that would not point to a `Quantity` object.

I'll look into it more on Monday.

**Comment by spencerkclark** [comment]
See #45 for a proposed fix.
